# Cyanea Marketing Website
# https://www.getzola.org/documentation/getting-started/configuration/

base_url = "https://cyanea.bio"
title = "Cyanea"
description = "Modern bioinformatics platform for genomic data management and analysis"
default_language = "en"

# Compilation settings
compile_sass = true
minify_html = false
build_search_index = true

# Feed settings
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]

[[taxonomies]]
name = "tags"
feed = true

[markdown]
smart_punctuation = true

[markdown.highlighting]
theme = "github-light"
style = "class"

[search]
include_title = true
include_description = true
include_path = true
include_content = true

[extra]
# Site-wide variables
author = "Cyanea Team"
github_url = "https://github.com/cyanea-io"
twitter_handle = "cyanea_io"

# Navigation
[[extra.nav]]
name = "Datasets"
url = "/datasets"

[[extra.nav]]
name = "Protocols"
url = "/protocols"

[[extra.nav]]
name = "Spaces"
url = "/spaces"

[[extra.nav]]
name = "Labs"
url = "/labs"

[[extra.nav]]
name = "Learn"
url = "/learn"

[[extra.nav]]
name = "Docs"
url = "/docs"
