# Cloudflare Pages configuration
# https://developers.cloudflare.com/pages/configuration/wrangler-configuration/

name = "cyanea-www"
pages_build_output_dir = "public"

[vars]
ZOLA_VERSION = "0.22.0"
